### ISSUE TITLE
Update TBD.amazonaws.com in transit-gateway-cloudtrail-logs.md

### ISSUE THREAD

**Issue by ranrotx** [awsdocs/aws-transit-gateway-guide#1]
In the section [Understanding Transit Gateway Log File Entries](https://github.com/awsdocs/aws-transit-gateway-guide/blob/master/doc_source/transit-gateway-cloudtrail-logs.md#understanding-transit-gateway-log-file-entries), the `eventSource` is referred to as `TBD.amazonaws.com`. This should probably be updated with the actual source (which looks to be `ec2.amazonaws.com` based on the sample log output).

**Comment by browndjaz** [comment]
Hi, 

I have updated the file to fix the "TBD".

https://github.com/awsdocs/aws-transit-gateway-guide/blob/master/doc_source/transit-gateway-cloudtrail-logs.md

Thank you,
Debbie Brown
