### ISSUE TITLE
Transit Gateway Isolated Shared is complete malarkey.

### ISSUE THREAD

**Issue by flyinprogrammer** [awsdocs/aws-transit-gateway-guide#13]
https://github.com/awsdocs/aws-transit-gateway-guide/blob/master/doc_source/transit-gateway-isolated-shared.md

You can't have the same Transit Gateway VPC Attachment attached to more than 1 Transit Gateway Route Table, and you can't create more than 1 Transit Gateway VPC Attachment per VPC.

Meaning this example with VPC D participating in multiple TG Route Tables is a complete figment of imagination.

Here's some example error messages you'll receive if you try and implement this:

```
Transit Gateway Attachment tgw-attach-064dcf3c96f3fbb9f is already associated to a route table.
```

```
DuplicateTransitGatewayAttachment: tgw-083e1180206738105 has non-deleted Transit Gateway Attachments with same VPC ID.
```

I wish you could though, because that's what I just tried to do. I ended up just going back to the 1 default route table that makes all routes possible, and then used standard VPC Route Table routes to control VPC connectivity.

Have y'all considered providing CloudFormation or Terraform sample code to actually prove to yourselves AWS documentation is actually possible before publishing it?

**Comment by flyinprogrammer** [comment]
https://github.com/flyinprogrammer/do_you_even_transit_gateway

**Comment by katerini** [comment]
Hello, thanks for your comment.

You're correct - you can't associate an attachment with more than one TGW route table. However, attachments' routes can be propagated to more than one route table. In this case, I don't think the scenario is suggesting that you associate the VPC D attachment with both route tables, but rather that you propagate its route (10.4.0.0/16) to both route tables. The docs could be clearer on this point though; apologies for the frustration this has caused. We'll revise the wording.
