### ISSUE TITLE
Black hole example

### ISSUE THREAD

**Issue by wolruf** [awsdocs/aws-transit-gateway-guide#3]
The Cloudwatch page mentions "blackhole route" via the metric PacketDropCountBlackhole
But there's no example of such Blackhole route in the documentation. Would be good to have an example.

**Comment by katerini** [comment]
Thanks for the feedback! We've added info about blackhole routes to the 'Routing' section:
https://github.com/awsdocs/aws-transit-gateway-guide/blob/master/doc_source/how-transit-gateways-work.md#routing

And we've added procedures on how to create blackhole routes:
https://github.com/awsdocs/aws-transit-gateway-guide/blob/master/doc_source/tgw-route-tables.md#create-a-static-route
