### ISSUE TITLE
"Isolated VPCs with shared services" example could do with more detail

### ISSUE THREAD

**Issue by bodgit** [awsdocs/aws-transit-gateway-guide#45]
I've just implemented the "Isolated VPCs with shared services" example and I found the documentation is a bit light on detail in regard to which route tables should be associated with and propagated to for each VPC. I initially associated and propagated each VPC to the same route table, it was only when I looked at the routes in each table that I realised it had propagated in the wrong direction. The fact that the shared services VPC is also intentionally propagated to both route tables could have been stated a bit clearer as I was looking at the example route tables and thinking it was a typo that VPC D appeared twice.

It would be useful to explicitly state:
* Each isolated VPC is associated with the isolated route table and propagated to the shared route table
* Each shared services VPC is associated with the shared route table and propagated to *both* route tables

If it's intended for clients on the end of the VPN connection to also access the shared services VPC, shouldn't the VPN route be propagated to both route tables also?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
