### ISSUE TITLE
Can number of CIDR per SA be documented ?

### ISSUE THREAD

**Issue by wolruf** [awsdocs/aws-transit-gateway-guide#6]
Hello,

As per troubleshooting guide:
https://aws.amazon.com/premiumsupport/knowledge-center/vpn-tunnel-troubleshooting/
Only 1 CIDR is allowed per Security Association.
Can this be documented directly in the documentation ?

**Comment by katerini** [comment]
Hi Olivier, thanks for the feedback. We do document the security association limit for VPN connections in the network admin guide:
https://docs.aws.amazon.com/vpc/latest/adminguide/Introduction.html#CGRequirements

The TGW guide doesn't go into details about VPN connections and their requirements. Would help if we linked to them though?

**Comment by wolruf** [comment]
Yes, it may help as customers may now directly start with TGW.

**Comment by katerini** [comment]
I've added links to the VPN documentation in various places:

- https://github.com/awsdocs/aws-transit-gateway-guide/blob/master/doc_source/tgw-vpn-attachments.md
- https://github.com/awsdocs/aws-transit-gateway-guide/blob/master/doc_source/transit-gateway-centralized-router.md
- https://github.com/awsdocs/aws-transit-gateway-guide/blob/master/doc_source/transit-gateway-isolated-shared.md
- https://github.com/awsdocs/aws-transit-gateway-guide/blob/master/doc_source/transit-gateway-isolated.md
